site_name: py-free-threading
repo_url: https://github.com/Quansight-Labs/free-threaded-compatibility
copyright: Copyright &copy; 2024- Quansight Labs & open source contributors

theme:
  name: material
  features:
    - header.autohide
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

nav:
  - 'index.md'
  - 'tracking.md'
  - 'installing_cpython.md'
  - 'running-gil-disabled.md'
  - 'porting.md'
  - 'ci.md'
  - 'debugging.md'

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Quansight-Labs/free-threaded-compatibility
    - icon: material/license
      link: https://github.com/Quansight-Labs/free-threaded-compatibility/blob/main/LICENSE
