site_name: Python Free-Threading Guide
repo_url: https://github.com/Quansight-Labs/free-threaded-compatibility
copyright: Copyright &copy; 2024- Quansight Labs & open source contributors

theme:
  name: material
  features:
    - content.code.copy
    - header.autohide
    - navigation.indexes
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

nav:
  - Index: 'index.md'
  - 'tracking.md'
  - 'installing-cpython.md'
  - 'running-gil-disabled.md'
  - Usage Examples:
    - 'examples/index.md'
    - 'examples/mandelbrot.md'
    - 'examples/monte-carlo.md'
    - 'examples/asyncio.md'
  - Porting Guide:
    - 'porting.md'
    - 'porting-extensions.md'
    - 'dependencies.md'
    - 'ci.md'
  - Testing, Debugging, and Profiling:
      - 'testing.md'
      - 'debugging.md'
      - 'thread_sanitizer.md'
      - 'profiling.md'
  - 'faq.md'
  - 'resources.md'
  - 'contributing.md'

# mkdocs-jupyter doesn't support putting notebooks in nav sections
# so exclude until that is fixed.
# See https://github.com/danielfrg/mkdocs-jupyter/issues/235.
not_in_nav: |
  examples/mandelbrot-threads.ipynb

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - mkdocs-jupyter

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - toc:
      permalink: "#"
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.blocks.caption

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Quansight-Labs/free-threaded-compatibility
    - icon: material/license
      link: https://github.com/Quansight-Labs/free-threaded-compatibility/blob/main/LICENSE

validation:
  omitted_files: warn
  absolute_links: warn
  not_found: warn
  unrecognized_links: warn
  anchors: warn
