name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy.yml'
      - 'docs/**'
      - 'mkdocs.yml'
      - 'requirements.txt'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/deploy.yml'
      - 'docs/**'
      - 'mkdocs.yml'
      - 'requirements.txt'

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: 3.12

      - name: Install MkDocs & co
        run: pip install -r requirements.txt

      - name: Build site
        run: mkdocs build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        with:
          personal_token: ${{ secrets.PYFREETHREADING_DEPLOY_KEY }}
          external_repository: py-free-threading/py-free-threading.github.io
          publish_branch: main
          publish_dir: ./site
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
